[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "naive"
dynamic = ["version", "description"]
authors = [{name = "David Doret"}]
maintainers = [{name = "David Doret"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Mathematics"]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.13.3",
    "nptyping>=2.1.3",
    "typing>=3.7.4.3",
    "dataclasses>=0.6"]

[project.urls]
Homepage = "https://github.com/daviddoret/naive"
Documentation = "https://naive.readthedocs.io/en/latest/index.html"
"Bug Tracker" = "https://github.com/scikit-hep/package/issues"
Discussions = "https://github.com/scikit-hep/package/discussions"
Changelog = "https://package.readthedocs.io/en/latest/changelog.html"

[tool.flit.sdist]
include = ["src/naive/"]
exclude = ["_trashcan/","tests","samples"]

