
# REPRESENTATION FORMATS
from _abc_representable import ABCRepresentable
from _class_glyph import Glyph
from _class_persisting_representable import PersistingRepresentable
from _class_symbol import Symbol
from _class_variable import Variable
from _class_variable_base import VariableBase
from _class_variable_indexes import VariableIndexes
from _exception_coercion_error import CoercionError
from _exception_coercion_warning import CoercionWarning
from _function_coerce import coerce
from _function_flatten import flatten
from _function_get_representation import get_representation
from _function_subscriptify import subscriptify
from _function_superscriptify import superscriptify


import rformats
import glyphs
import notation

# SYMBOL DEFINITION
from i_defining_element_abstract_class import ISymbolDefiningElement
from i_defined_element_abstract_class import ISymbolDefinedElement
from i_definition_abstract_class import ISymbolDefinition


