"""Package settings

todo:
    * Consider using a python settings package such as python-settings or simple-settings
"""

# Math notation
UNKNOWN_NOTATION = '?'
VARIABLE_NO_INDEX = ''
NATURAL_NUMBER_0_DOMAIN_NOTATION = 'ℕ₀'
NATURAL_NUMBER_1_DOMAIN_NOTATION = 'ℕ₁'
BINARY_NUMBER_DOMAIN_NOTATION = '𝔹'
N_TUPLE_DOMAIN_NOTATION = 'N-Tuple'
ENVIRONMENT_DOMAIN_NOTATION = 'Environment'
BINARY_VALUE_0_NOTATION = '⊥'
BINARY_VALUE_1_NOTATION = '⊤'
DEFAULT_USER_ENVIRONMENT_BASE_NAME = 'U'
ELEMENT_OF_NOTATION = '∈'
EQUALITY_NOTATION = '='
VARIABLE_SCOPE_SEPARATOR_NOTATION = '.'
